Allow trans / endtrans tags
MalteJanz/ludtwig pull request #125
Opened 2024-11-29 07:39 UTC by freezernick

Closes #124

2024-12-03 15:14 UTC, freezernick commented
I've added a test and removed the loop from the method.
The `env UPDATE_EXPECT=1 cargo test grammar::twig:tags::parse_twig_trans` didn't seem to work for me, maybe I missed something...

Putting this in an optional rule would be fine for us / our customer.
While I don't see any direct disadvantages by having this activated by default, it *may* happen that someone copies a Drupal twig template in their vanilla twig project, run into an error, check it with ludtwig and don't get an error about unknown syntax / tags...

2024-12-03 16:37 UTC, MalteJanz requested changes
> I've added a test and removed the loop from the method. The `env UPDATE_EXPECT=1 cargo test grammar::twig:tags::parse_twig_trans` didn't seem to work for me, maybe I missed something...

Mh, you can also try just running `UPDATE_EXPECT=1 cargo test` but that might touch other tests. Anyways you can of course also copy the expected output manually from the failed test...

> Putting this in an optional rule would be fine for us / our customer. While I don't see any direct disadvantages by having this activated by default, it _may_ happen that someone copies a Drupal twig template in their vanilla twig project, run into an error, check it with ludtwig and don't get an error about unknown syntax / tags...

Just to clarify, I distinguished between the parser (this PR) and rules (e. g. 
https://github.com/MalteJanz/ludtwig/blob/da850a17d0d3b72f0bca94a94b33f25a052e5a36/crates/ludtwig/src/check/rules/twig_logic_and.rs )

The former is always active and ensures all twig source code gets parsed into a syntax tree (can still contain some invalid syntax which gets wrapped up in error nodes, these would also be reported). The latter is the actual "linting" part that checks this syntax tree and makes suggestions (based on rules).

So this PR allows ludtwig to parse these `{% trans %} hello world {% endtrans%}` blocks with any children. It's up to the rules to annotate something wrong there (e.g. reporting any trans blocks with empty body).

Means if your project doesn't support `trans` and you still use it in your template, ludtwig itself will not report any errors after this PR gets merged. But that would be fine to me, we also allow for example shopware's syntax extensions like `||` instead of `or`, but for that at least we have a rule to suggest sticking to `or` as that is native twig

But feel free to add those rules in a later PR if you want 😉

2024-12-03 16:37 UTC, MalteJanz commented on crates/ludtwig-parser/src/grammar/twig/tags.rs
> +                TWIG_TRANS@0..38
So this is basically your `TWIG_TRANS` element and if I look at the provided twig code I would expect it to contain:
- `TWIG_TRANS_STARTING_BLOCK` => `{% trans %}`
- `BODY` => ` hello world`
- `TWIG_TRANS_ENDING_BLOCK` => ` {% endtrans %}`

Right now it contains `TWIG_TRANS ` two times (the inner is the starting block) and is missing the `BODY` wrapper around all child nodes.

2024-12-03 16:37 UTC, MalteJanz commented on crates/ludtwig-parser/src/syntax/untyped.rs
> +    TWIG_ENDTRANS_BLOCK,
As mentioned above, for the syntax nodes I would suggest something similar to the basic twig block:
```rust

    // twig block
    TWIG_BLOCK,
    TWIG_STARTING_BLOCK,
    TWIG_ENDING_BLOCK,
    
     // twig sandbox
    TWIG_SANDBOX,
    TWIG_SANDBOX_STARTING_BLOCK,
    TWIG_SANDBOX_ENDING_BLOCK,
```
So after seeing how the twig code for this looks like I would propose:
```rust
     // Drupal Trans
    TWIG_TRANS,
    TWIG_TRANS_STARTING_BLOCK,
    TWIG_TRANS_ENDING_BLOCK,
```

2024-12-03 16:37 UTC, MalteJanz commented on crates/ludtwig-parser/src/grammar/twig/tags.rs
> +  let wrapper_m = parser.complete(outer, SyntaxKind::TWIG_TRANS);
```suggestion
  let wrapper_m = parser.complete(outer, SyntaxKind::TWIG_TRANS_STARTING_BLOCK);
```

2024-12-03 16:37 UTC, MalteJanz commented on crates/ludtwig-parser/src/grammar/twig/tags.rs
> +);
```suggestion
  // parse all the children except endtrans
  let body_m = parser.start();
  parse_many(
    parser,
    |p| {
        p.at_following(&[T!["{%"], T!["endtrans"]])
    },
    |p| {
        child_parser(p);
    },
  );
  parser.complete(body_m, SyntaxKind::BODY);
```

2024-12-03 16:37 UTC, MalteJanz commented on crates/ludtwig-parser/src/grammar/twig/tags.rs
> +  parser.complete(end_block_m, SyntaxKind::TWIG_ENDTRANS_BLOCK);
```suggestion
  parser.complete(end_block_m, SyntaxKind::TWIG_TRANS_ENDING_BLOCK);
```

2024-12-03 16:37 UTC, MalteJanz commented on crates/ludtwig-parser/src/syntax/untyped.rs
> +    TWIG_ENDTRANS_BLOCK,
One other thing I forgot to mention, you should add AST structs for these. Have a look here https://github.com/MalteJanz/ludtwig/blob/da850a17d0d3b72f0bca94a94b33f25a052e5a36/crates/ludtwig-parser/src/syntax/typed.rs#L523-L531

You can also add utility methods if you like (can be useful to work with that AST node in rules that check specific things about these `trans` blocks), see for example the AST implementation for twig blocks:

https://github.com/MalteJanz/ludtwig/blob/da850a17d0d3b72f0bca94a94b33f25a052e5a36/crates/ludtwig-parser/src/syntax/typed.rs#L82-L137

2025-02-17 15:18 UTC, freezernick commented
Closing in favor of #138

2025-02-17 15:18 UTC, closed without merging